spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/geo_atlas_db_v100
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_SECRET}

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:geo-atlas@fuyi}

geo-atlas:
  cache:
    enabled: true
    inner-caching-enabled: false
    persistence-enabled: true # 默认是file-system
    inner:
      storage:
        eviction-policy: EXPIRE_AFTER_ACCESS
        memory-limit: 256
    persistence:
      storage:
        base-directory: ${PERSISTENCE_CACHE_DIR:/tmp/gac}

logging:
  level:
    #    root: TRACE
    root: INFO
    org.geoatlas: DEBUG
    org.geotools.jdbc: DEBUG
    org.springframework.jdbc.core: DEBUG